package org.silverbulleters.bsl.platform.context.types;

public enum ModuleType {
    MANAGED_APPLICATION_MODULE, SESSION_MODULE, EXTERNAL_CONNECTION_MODULE, COMMAND_MODULE, MANAGER_MODULE, OBJECT_MODULE, RECORD_SET_MODULE, FORM_MODULE
}
