package org.silverbulleters.bsl.platform.context.types;

public enum ObjectType {
    CATALOG, DOCUMENT, APPLICATION, EXCHANGE_PLAN, COMMON_FORM, COMMON_COMMAND, CONSTANT, DOCUMENT_JOURNAL,
    ENUM, REPORT, EXTERNAL_DATA_PROCESSOR, CHART_OF_CHARACTERISTIC_TYPES, CHART_OF_ACCOUNTS, CHART_OF_CALCULATION_TYPES,
    INFORMATION_REGISTER, ACCUMULATION_REGISTER, ACCOUNTING_REGISTER, CALCULATION_REGISTER, BUSINESS_PROCESS, TASK
}
