name: Check project

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: [ '11' ]
        os: [ 'ubuntu-latest', 'windows-latest', 'macOS-latest' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: ''

      - name: Setup JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2.1.0
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'adopt-hotspot'

      - name: Build
        run: ./gradlew check

      - name: Archive test results
        uses: actions/upload-artifact@v2.2.4
        with:
          name: junit_${{ matrix.os }}_${{ matrix.java_version }}
          path: build/reports/tests/test

      - name: Static code analysis
        if: matrix.java_version == '11' && matrix.os == 'ubuntu-latest'
        run: ./gradlew sonarqube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
